import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { UserProvider } from "@/contexts/UserContext";
import React from "react";
import { PostProvider } from "@/contexts/PostContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
          <body className={inter.className}>
            <AuthProvider>
              <UserProvider>
                <PostProvider>
                   { children }
                </PostProvider>
              </UserProvider>
            </AuthProvider>
          </body>
    </html>
  );
}
